### PR TITLE
Pages versioning

### PR DESCRIPTION
**Pull request by AidanCurrah**
This PR adds versioning functionality to the CMS that can be controlled through a setting. Add one DB hit to pages middleware but otherwise shouldn't affect frontend performance.

---
- [x] This pull request updates the CHANGELOG.
- [ ] If this adds any new functionality or changes existing behaviour, this pull request updates the documentation.

### CODE REVIEW

**Review by daniel-clayton — CHANGES_REQUESTED** [review]
Got a general suggestion on how you could tweak this functionality slightly, so I'll save any small review points for now...

As I understand it this is piggybacking on the existing language version functionality, so using `owner` and differentiating the versions by number and then getting the latest version for a language (if enabled) in the middleware.

However, I think there's an important distinction between the language versions and "content" versions of pages. We only know what language a user wants at the point a request is made, so we have to look for the correct version in the middleware. With content versions we already know which version we should show to the user before the request is made because we don't care about old versions (except for staff members).

There might be another way of handling it but here is my suggestion:
Add another foreign key relation to `page` on the `Page` model and call it something like `version_for`, keep `version` for ordering purposes and `verbose_name` `owner` to something more language specific. Then in the `PageManager` by default we can filter out any pages that have `version_for` set and we can either add another middleware class `VersioningMiddleware` or extend `PublicationMiddleware` to serve up different versions on the frontend for admins.

Caveats to the above:
- It should only be possible to make versions for pages that don't have `version_for` and `owner` set, essentially just the root page. Alternatively: restrict versions to the language of its parent.
- Content will need to be copied over when making a page the 'live' version (or you could shuffle the foreign keys to make it the root object but that seems more sketchy)
- When updating a language version it will have to look at its owner's `version_set`

**Comment by daniel-clayton** [comment]
Also should be just get rid of Reversion when we are happy with this and save backup versions instead?

**Comment by charley-rose** [comment]
Once you've created a duplicate of the site (creating a new version) the save button still appears and can continue to be pressed but nothing else happens. Should we have this removed after pressing once and a green success bar appear confirming you've created a new version?

image

**Comment by charley-rose** [comment]
When you save a page, the save successful message lists the title of the page as being saved successfully, can we include which version has also been saved in the message to avoid any confusion.

image

**Comment by charley-rose** [comment]
On the in-between page where you can view different page versions, should there be a breadcrumb nav and potentially a new step after 'pages > pages' so you can click back through the breadcrumb to see the list view of page versions rather than only being able to go to the pages list.

image

image

**Comment by charley-rose** [comment]
I can only make new versions from the 1st version page, if I select 'Add version' whilst editing a draft page, it takes me back to the list and a new version has not been created.

**Comment by charley-rose** [comment]
When working on a draft page, the other save options don't work properly, should they be there? The duplicate option returns a 500 internal server error, save and add another just refreshes the same page and save and return takes you to the pages list instead of the versions list.

image

**Comment by charley-rose** [comment]
The make live version option isn't very noticeable and isn't obvious that it's editable. Can we make it a checkbox similar to the online option on the pages list.

image


image

**Comment by AidanCurrah** [comment]
@charley-rose 
> Once you've created a duplicate of the site (creating a new version) the save button still appears and can continue to be pressed but nothing else happens. Should we have this removed after pressing once and a green success bar appear confirming you've created a new version?
> 
> **Update:** After looking through more of the draft mode, this 'Editing page with draft versions' box appears even when not duplicating a page, is this meant to be at the top?

For this, the box at the top is to edit a particular page's slug and parent page as this has ramifications across all versions of a page instead of just the one you're editing. I could maybe make this clearer



> When you save a page, the save successful message lists the title of the page as being saved successfully, can we include which version has also been saved in the message to avoid any confusion.

This is kind-of awkward to change. I'll leave it as is for now and have a look at adjusting later. This isn't a priority to change



> On the in-between page where you can view different page versions, should there be a breadcrumb nav and potentially a new step after 'pages > pages' so you can click back through the breadcrumb to see the list view of page versions rather than only being able to go to the pages list.

I've adjusted this so the breadcrumbs on the edit versions list page works correctly now and I've inserted an intermediate step on the change page if that page has versions to take you back to the version list page.



> I can only make new versions from the 1st version page, if I select 'Add version' whilst editing a draft page, it takes me back to the list and a new version has not been created.

I've fixed this issue. The problem was that if you made a new version while on a version page, you'd make a version for that page rather than the parent page.



> When working on a draft page, the other save options don't work properly, should they be there? The duplicate option returns a 500 internal server error, save and add another just refreshes the same page and save and return takes you to the pages list instead of the versions list.

This error is only thrown if you select the 'Duplicate page' option however it shouldn't happen so I'll either hide this option or fix the underlying issue



> The make live version option isn't very noticeable and isn't obvious that it's editable. Can we make it a checkbox similar to the online option on the pages list.

If I make it a checkbox, we'd need a 'Save' button underneath. Would you prefer this or I could make the 'Make live' text into buttons themselves so it's more obvious that they're actions.

**Pull request merged**
